### ISSUE TITLE
Update role

### ISSUE THREAD

**Issue by llillo** [angelochillemix/pmi-users-sync#4]
Based on PMI-ID, needs to be updated the user role with flags PMI and PMI-SIC.
If PMI-ID is not found, only PMI-SIC role is removed.
A custom flag in Setting should be provided for activate/deactivate this option.

**Comment by angelochillemix** [comment]
@llillo as discussed, requirements as follows:

* Loop the entire users database to match them with those coming from Excel file or DEP Web Service, instead of the opposite
* Match the email first. If email is not found, then match the PMI-ID:

**if found**
* Based on the overwriting flag in the settings overwrite the PMI-ID
* Assign the role and membership (i.e. Socio PMI and Socio PMI-SIC) to the user

**If not found**
* Remove PMI-SIC role and membership from the user's profile, keeping PMI membership
