### ISSUE TITLE
Show sync loader and last sync info

### ISSUE THREAD

**Issue by llillo** [angelochillemix/pmi-users-sync#6]
On PMI Users page show the sync loader that has been set on Settings and show last sync date and time

**Comment by angelochillemix** [comment]
@llillo we'll add the lst sync date and time.

However, regarding the loader selected it is already the case, since the Heading takes it in consideration:

### Excel file
![image](https://user-images.githubusercontent.com/13917784/148652953-e0d47e70-6678-4ab2-93cf-60e6cf4885f2.png)

In such case, the Excel file path is printed on the page.

### Web Service
![image](https://user-images.githubusercontent.com/13917784/148653100-1a6e9014-56f0-4f79-9917-12bf2c5da8a6.png)

If not clear enough we could find another way to present it.

**Comment by angelochillemix** [comment]
Implementation done and ready for validation.

![image](https://user-images.githubusercontent.com/13917784/148661777-f5431289-734c-41ff-ba4b-ec922ce87574.png)

**Comment by llillo** [comment]
Great, we can close this issue
